## Copyright (C) 2017 Jeremiah Orians
## This file is part of stage0.
##
## stage0 is free software: you an redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## stage0 is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with stage0.  If not, see <http://www.gnu.org/licenses/>.

* Current
** Added
Added a greeting to the standard ascension.scm
Added ability to turn on and off echo to make bootup quieter
Added #\a through #\z
Added get-type and set-type! primitives to allow easy addition of new types
Added list pair-up function
Added basic error function to halt in weird edge cases
Added some special chars
Added env-bind
added env-lookup
Added while primitive
Added read-byte primitive
Added support for Hex numbers being read in provided they are prefixed by 0x
Added ability to select file output
Added ability to select console output
Added ability to change memory allocation
Added M2-Planet build target and script
Added support for reading and writing to files

** Changed
Altered order of arguments in list_to_string function to simplify assembly implementation
Now hides all new definitions loading
Display string of unbound symbol to aid in debugging
Made assoc more flexible
Made set-type be a copying rather than overwriting operation
Gave assoc better names and let it return nil when none are found
Broke out non-standard functions into lisp.scm
Changed the behavior of (while #t (expression)) to allow for infinite loops
Changed behavior of write
Harmonized M2-Planet build behavior with mescc-tools 0.6.0 release

** Fixed
Fixed bug in line comments
Fixed bug in eq? such that it behaves correctly with strings
Program now behaves correctly when given bad file names
Fixed broken makefile

** Removed
Removed multiple type functions from Slow_lisp binary and into the ascension library
Removed redundent evaluation paths
Removed redundent function calls in regards to the number of free cells

* 0.2 - 2017-07-19
** Added
Added number?
Added string-append
Added Get-index
Added map
Added filter
Added length
Added string-length
Added eq?
Added fold-left
Added symbol?
Exported apply functionality

** Changed
Changed reverse to not depend on alternate functions

** Fixed

** Removed
Removed reving as it is only needed inside of reverse

* 0.1 - 2017-07-01
** Added
Added inital changelog
Added version message
Added Help message
Added support for multiple definition files
Added Test0 to demonstrate support for quote
Added Test1 to demonstrate support for list, cons, car, cdr, null? and cond
Added test target to make
Added support for raw strings
Added recursive support to integer->char
Added char->integer
Added string->list
Added char?
Added string?
Added list->string
Added initial lisp ascension library
Extending lisp ascension library with reverse, fold-right and a couple char functions
Added cell list reversing primitive

** Changed
Makefile is modified to follow bin standard
Renamed resulting binary to slow_lisp to prevent namespace conflicts in bin
Enhanced basic tests
Converted ASCII type to CHAR
Converted ASCII! to integer->char
Made integer->char match guile

** Fixed
makefile now does proper cleanup
Harmonized max_string size that doesn't hit glibc malloc bug

** Removed
Removed C warning about unused args in prim_halt
Removed need for append cell

* 0.0 - 2017-07-01
** Added
Inital important of Stage0 lisp, high level prototype

** Changed

** Fixed

** Removed
